version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"

    # Use this if you want a to map to a dir on host machine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
# Use this if you want a docker volume

# volumes:
#   - postgres_data:/var/lib/postgresql/data

# Use this if you want a docker volume
# volumes:
#   postgres_data:/var/lib/postgresql/data:
